import math
a = int(input("digite a "))
b = int(input("digite b "))
c = int(input("digite c "))
c_a =float( ( ((a*a)-(b*b)-(c*c)) / (-2*b*c) ))
c_b =float( ( ((b*b)-(a*a)-(c*c)) / (-2*a*c) ))
c_c =float( ( ((c*c)-(b*b)-(a*a)) / (-2*b*a) ))
print("O angulos de A =  ",math.degrees(math.acos(c_a)))
print("O angulos de B =  ",math.degrees(math.acos(c_b)))
print("O angulos de c =  ",math.degrees(math.acos(c_c)))
