lista = input().split(' ')
a = float(lista[0])
b = float(lista[1])
c = float(lista[2])
print("TRIANGULO: %0.3f"%((a*c)/2) )
print("CIRCULO: %0.3f"%(c*c*(3.14159)))
print("TRAPEZIO: %0.3f"%((a+b)*c/2))
print("QUADRADO: %0.3f"%(b*b))
print("RETANGULO: %0.3f"%(a*b))
